"""Original A1 starter vocabulary written specifically for German learners."""
from __future__ import annotations


def _noun(de: str, tr: str, en: str, article: str, plural: str, rank: int, deck: str):
    gender = {"der": "masculine", "die": "feminine", "das": "neuter"}[article]
    return {
        "de": de, "tr": tr, "en": en, "article": article, "gender": gender,
        "plural": plural, "part_of_speech": "noun",
        "example_de": f"Das ist {article} {de}.",
        "example_tr": f"Bu, {tr}.", "example_en": f"This is the {en}.",
        "frequency_rank": rank, "deck": deck, "audio": "",
    }


def _word(de: str, tr: str, en: str, pos: str, ex_de: str, ex_tr: str,
          ex_en: str, rank: int, deck: str):
    return {
        "de": de, "tr": tr, "en": en, "article": "", "gender": "",
        "plural": "", "part_of_speech": pos, "example_de": ex_de,
        "example_tr": ex_tr, "example_en": ex_en, "frequency_rank": rank,
        "deck": deck, "audio": "",
    }


_NOUN_DATA = [
    ("Mann", "adam", "man", "der", "Männer", "İnsanlar"),
    ("Frau", "kadın", "woman", "die", "Frauen", "İnsanlar"),
    ("Kind", "çocuk", "child", "das", "Kinder", "İnsanlar"),
    ("Junge", "erkek çocuk", "boy", "der", "Jungen", "İnsanlar"),
    ("Mädchen", "kız çocuk", "girl", "das", "Mädchen", "İnsanlar"),
    ("Freund", "erkek arkadaş", "friend", "der", "Freunde", "İnsanlar"),
    ("Freundin", "kadın arkadaş", "friend", "die", "Freundinnen", "İnsanlar"),
    ("Mutter", "anne", "mother", "die", "Mütter", "Aile"),
    ("Vater", "baba", "father", "der", "Väter", "Aile"),
    ("Bruder", "erkek kardeş", "brother", "der", "Brüder", "Aile"),
    ("Schwester", "kız kardeş", "sister", "die", "Schwestern", "Aile"),
    ("Familie", "aile", "family", "die", "Familien", "Aile"),
    ("Name", "isim", "name", "der", "Namen", "Temel"),
    ("Lehrer", "erkek öğretmen", "teacher", "der", "Lehrer", "Okul"),
    ("Lehrerin", "kadın öğretmen", "teacher", "die", "Lehrerinnen", "Okul"),
    ("Schüler", "öğrenci", "pupil", "der", "Schüler", "Okul"),
    ("Arzt", "doktor", "doctor", "der", "Ärzte", "Meslekler"),
    ("Ärztin", "kadın doktor", "doctor", "die", "Ärztinnen", "Meslekler"),
    ("Haus", "ev", "house", "das", "Häuser", "Ev"),
    ("Wohnung", "daire", "apartment", "die", "Wohnungen", "Ev"),
    ("Zimmer", "oda", "room", "das", "Zimmer", "Ev"),
    ("Küche", "mutfak", "kitchen", "die", "Küchen", "Ev"),
    ("Bad", "banyo", "bathroom", "das", "Bäder", "Ev"),
    ("Tür", "kapı", "door", "die", "Türen", "Ev"),
    ("Fenster", "pencere", "window", "das", "Fenster", "Ev"),
    ("Tisch", "masa", "table", "der", "Tische", "Ev"),
    ("Stuhl", "sandalye", "chair", "der", "Stühle", "Ev"),
    ("Bett", "yatak", "bed", "das", "Betten", "Ev"),
    ("Lampe", "lamba", "lamp", "die", "Lampen", "Ev"),
    ("Schlüssel", "anahtar", "key", "der", "Schlüssel", "Ev"),
    ("Buch", "kitap", "book", "das", "Bücher", "Okul"),
    ("Heft", "defter", "notebook", "das", "Hefte", "Okul"),
    ("Stift", "kalem", "pen", "der", "Stifte", "Okul"),
    ("Schule", "okul", "school", "die", "Schulen", "Okul"),
    ("Sprache", "dil", "language", "die", "Sprachen", "Okul"),
    ("Wort", "kelime", "word", "das", "Wörter", "Okul"),
    ("Frage", "soru", "question", "die", "Fragen", "Okul"),
    ("Antwort", "cevap", "answer", "die", "Antworten", "Okul"),
    ("Stadt", "şehir", "city", "die", "Städte", "Yerler"),
    ("Land", "ülke", "country", "das", "Länder", "Yerler"),
    ("Straße", "sokak", "street", "die", "Straßen", "Yerler"),
    ("Platz", "meydan", "square", "der", "Plätze", "Yerler"),
    ("Bahnhof", "tren istasyonu", "station", "der", "Bahnhöfe", "Ulaşım"),
    ("Flughafen", "havaalanı", "airport", "der", "Flughäfen", "Ulaşım"),
    ("Hotel", "otel", "hotel", "das", "Hotels", "Seyahat"),
    ("Restaurant", "restoran", "restaurant", "das", "Restaurants", "Seyahat"),
    ("Geschäft", "mağaza", "shop", "das", "Geschäfte", "Alışveriş"),
    ("Markt", "pazar", "market", "der", "Märkte", "Alışveriş"),
    ("Auto", "araba", "car", "das", "Autos", "Ulaşım"),
    ("Bus", "otobüs", "bus", "der", "Busse", "Ulaşım"),
    ("Zug", "tren", "train", "der", "Züge", "Ulaşım"),
    ("Fahrrad", "bisiklet", "bicycle", "das", "Fahrräder", "Ulaşım"),
    ("Ticket", "bilet", "ticket", "das", "Tickets", "Ulaşım"),
    ("Wasser", "su", "water", "das", "-", "Yiyecek"),
    ("Brot", "ekmek", "bread", "das", "Brote", "Yiyecek"),
    ("Milch", "süt", "milk", "die", "-", "Yiyecek"),
    ("Kaffee", "kahve", "coffee", "der", "Kaffees", "Yiyecek"),
    ("Tee", "çay", "tea", "der", "Tees", "Yiyecek"),
    ("Apfel", "elma", "apple", "der", "Äpfel", "Yiyecek"),
    ("Banane", "muz", "banana", "die", "Bananen", "Yiyecek"),
    ("Kartoffel", "patates", "potato", "die", "Kartoffeln", "Yiyecek"),
    ("Tomate", "domates", "tomato", "die", "Tomaten", "Yiyecek"),
    ("Käse", "peynir", "cheese", "der", "-", "Yiyecek"),
    ("Ei", "yumurta", "egg", "das", "Eier", "Yiyecek"),
    ("Fleisch", "et", "meat", "das", "-", "Yiyecek"),
    ("Fisch", "balık", "fish", "der", "Fische", "Yiyecek"),
    ("Suppe", "çorba", "soup", "die", "Suppen", "Yiyecek"),
    ("Frühstück", "kahvaltı", "breakfast", "das", "Frühstücke", "Yiyecek"),
    ("Kopf", "baş", "head", "der", "Köpfe", "Vücut"),
    ("Hand", "el", "hand", "die", "Hände", "Vücut"),
    ("Auge", "göz", "eye", "das", "Augen", "Vücut"),
    ("Ohr", "kulak", "ear", "das", "Ohren", "Vücut"),
    ("Mund", "ağız", "mouth", "der", "Münder", "Vücut"),
    ("Fuß", "ayak", "foot", "der", "Füße", "Vücut"),
    ("Tag", "gün", "day", "der", "Tage", "Zaman"),
    ("Woche", "hafta", "week", "die", "Wochen", "Zaman"),
    ("Monat", "ay", "month", "der", "Monate", "Zaman"),
    ("Jahr", "yıl", "year", "das", "Jahre", "Zaman"),
    ("Morgen", "sabah", "morning", "der", "Morgen", "Zaman"),
    ("Abend", "akşam", "evening", "der", "Abende", "Zaman"),
    ("Uhr", "saat", "clock", "die", "Uhren", "Zaman"),
    ("Wetter", "hava", "weather", "das", "-", "Doğa"),
    ("Sonne", "güneş", "sun", "die", "Sonnen", "Doğa"),
    ("Regen", "yağmur", "rain", "der", "-", "Doğa"),
    ("Schnee", "kar", "snow", "der", "-", "Doğa"),
    ("Baum", "ağaç", "tree", "der", "Bäume", "Doğa"),
    ("Blume", "çiçek", "flower", "die", "Blumen", "Doğa"),
    ("Hund", "köpek", "dog", "der", "Hunde", "Hayvanlar"),
    ("Katze", "kedi", "cat", "die", "Katzen", "Hayvanlar"),
    ("Arbeit", "iş", "work", "die", "Arbeiten", "Günlük"),
    ("Büro", "ofis", "office", "das", "Büros", "Günlük"),
    ("Geld", "para", "money", "das", "-", "Alışveriş"),
    ("Preis", "fiyat", "price", "der", "Preise", "Alışveriş"),
    ("Telefon", "telefon", "telephone", "das", "Telefone", "Günlük"),
    ("Computer", "bilgisayar", "computer", "der", "Computer", "Günlük"),
    ("Musik", "müzik", "music", "die", "-", "Boş Zaman"),
    ("Film", "film", "film", "der", "Filme", "Boş Zaman"),
    ("Spiel", "oyun", "game", "das", "Spiele", "Boş Zaman"),
    ("Geburtstag", "doğum günü", "birthday", "der", "Geburtstage", "Günlük"),
    ("Hilfe", "yardım", "help", "die", "-", "Temel"),
]

WORDS = [_noun(de, tr, en, article, plural, i + 1, deck)
         for i, (de, tr, en, article, plural, deck) in enumerate(_NOUN_DATA)]

_OTHER_DATA = [
    ("sein", "olmak", "to be", "verb", "Ich bin heute zu Hause.", "Bugün evdeyim.", "I am at home today.", "Fiiller"),
    ("haben", "sahip olmak", "to have", "verb", "Wir haben zwei Kinder.", "İki çocuğumuz var.", "We have two children.", "Fiiller"),
    ("heißen", "adı olmak", "to be called", "verb", "Ich heiße Anna.", "Benim adım Anna.", "My name is Anna.", "Fiiller"),
    ("wohnen", "oturmak", "to live", "verb", "Ich wohne in Berlin.", "Berlin'de oturuyorum.", "I live in Berlin.", "Fiiller"),
    ("kommen", "gelmek", "to come", "verb", "Sie kommt aus Köln.", "O, Köln'den geliyor.", "She comes from Cologne.", "Fiiller"),
    ("gehen", "gitmek", "to go", "verb", "Wir gehen zur Schule.", "Okula gidiyoruz.", "We go to school.", "Fiiller"),
    ("fahren", "araçla gitmek", "to travel", "verb", "Er fährt mit dem Bus.", "Otobüsle gidiyor.", "He travels by bus.", "Fiiller"),
    ("machen", "yapmak", "to do", "verb", "Was machst du heute?", "Bugün ne yapıyorsun?", "What are you doing today?", "Fiiller"),
    ("lernen", "öğrenmek", "to learn", "verb", "Ich lerne Deutsch.", "Almanca öğreniyorum.", "I am learning German.", "Fiiller"),
    ("arbeiten", "çalışmak", "to work", "verb", "Mein Vater arbeitet hier.", "Babam burada çalışıyor.", "My father works here.", "Fiiller"),
    ("sprechen", "konuşmak", "to speak", "verb", "Sprichst du Englisch?", "İngilizce konuşuyor musun?", "Do you speak English?", "Fiiller"),
    ("sagen", "söylemek", "to say", "verb", "Bitte sag deinen Namen.", "Lütfen adını söyle.", "Please say your name.", "Fiiller"),
    ("fragen", "sormak", "to ask", "verb", "Ich frage den Lehrer.", "Öğretmene soruyorum.", "I ask the teacher.", "Fiiller"),
    ("antworten", "cevap vermek", "to answer", "verb", "Sie antwortet auf Deutsch.", "Almanca cevap veriyor.", "She answers in German.", "Fiiller"),
    ("lesen", "okumak", "to read", "verb", "Er liest ein Buch.", "Bir kitap okuyor.", "He is reading a book.", "Fiiller"),
    ("schreiben", "yazmak", "to write", "verb", "Ich schreibe eine E-Mail.", "Bir e-posta yazıyorum.", "I am writing an email.", "Fiiller"),
    ("hören", "dinlemek", "to hear", "verb", "Wir hören Musik.", "Müzik dinliyoruz.", "We listen to music.", "Fiiller"),
    ("sehen", "görmek", "to see", "verb", "Ich sehe den Zug.", "Treni görüyorum.", "I see the train.", "Fiiller"),
    ("essen", "yemek", "to eat", "verb", "Das Kind isst einen Apfel.", "Çocuk bir elma yiyor.", "The child is eating an apple.", "Fiiller"),
    ("trinken", "içmek", "to drink", "verb", "Möchtest du Tee trinken?", "Çay içmek ister misin?", "Would you like to drink tea?", "Fiiller"),
    ("kaufen", "satın almak", "to buy", "verb", "Wir kaufen frisches Brot.", "Taze ekmek alıyoruz.", "We buy fresh bread.", "Fiiller"),
    ("bezahlen", "ödemek", "to pay", "verb", "Ich bezahle mit Karte.", "Kartla ödüyorum.", "I pay by card.", "Fiiller"),
    ("brauchen", "ihtiyacı olmak", "to need", "verb", "Ich brauche Hilfe.", "Yardıma ihtiyacım var.", "I need help.", "Fiiller"),
    ("mögen", "sevmek", "to like", "verb", "Wir mögen diesen Film.", "Bu filmi seviyoruz.", "We like this film.", "Fiiller"),
    ("möchten", "istemek", "would like", "verb", "Ich möchte einen Kaffee.", "Bir kahve istiyorum.", "I would like a coffee.", "Fiiller"),
    ("können", "-ebilmek", "can", "verb", "Kannst du mir helfen?", "Bana yardım edebilir misin?", "Can you help me?", "Fiiller"),
    ("müssen", "zorunda olmak", "must", "verb", "Ich muss jetzt gehen.", "Şimdi gitmek zorundayım.", "I must go now.", "Fiiller"),
    ("wollen", "istemek", "to want", "verb", "Wir wollen nach Hause.", "Eve gitmek istiyoruz.", "We want to go home.", "Fiiller"),
    ("geben", "vermek", "to give", "verb", "Gib mir bitte das Buch.", "Lütfen kitabı bana ver.", "Please give me the book.", "Fiiller"),
    ("nehmen", "almak", "to take", "verb", "Ich nehme den Zug.", "Trene biniyorum.", "I take the train.", "Fiiller"),
    ("finden", "bulmak", "to find", "verb", "Sie findet den Schlüssel.", "Anahtarı buluyor.", "She finds the key.", "Fiiller"),
    ("suchen", "aramak", "to look for", "verb", "Ich suche ein Hotel.", "Bir otel arıyorum.", "I am looking for a hotel.", "Fiiller"),
    ("öffnen", "açmak", "to open", "verb", "Bitte öffnen Sie das Fenster.", "Lütfen pencereyi açın.", "Please open the window.", "Fiiller"),
    ("schließen", "kapatmak", "to close", "verb", "Er schließt die Tür.", "Kapıyı kapatıyor.", "He closes the door.", "Fiiller"),
    ("schlafen", "uyumak", "to sleep", "verb", "Das Baby schläft.", "Bebek uyuyor.", "The baby is sleeping.", "Fiiller"),
    ("gut", "iyi", "good", "adjective", "Der Kaffee ist gut.", "Kahve iyi.", "The coffee is good.", "Sıfatlar"),
    ("schlecht", "kötü", "bad", "adjective", "Das Wetter ist schlecht.", "Hava kötü.", "The weather is bad.", "Sıfatlar"),
    ("groß", "büyük", "big", "adjective", "Berlin ist eine große Stadt.", "Berlin büyük bir şehirdir.", "Berlin is a big city.", "Sıfatlar"),
    ("klein", "küçük", "small", "adjective", "Das Zimmer ist klein.", "Oda küçük.", "The room is small.", "Sıfatlar"),
    ("neu", "yeni", "new", "adjective", "Mein Fahrrad ist neu.", "Bisikletim yeni.", "My bicycle is new.", "Sıfatlar"),
    ("alt", "eski; yaşlı", "old", "adjective", "Das Haus ist sehr alt.", "Ev çok eski.", "The house is very old.", "Sıfatlar"),
    ("jung", "genç", "young", "adjective", "Die Lehrerin ist jung.", "Öğretmen genç.", "The teacher is young.", "Sıfatlar"),
    ("schön", "güzel", "beautiful", "adjective", "Der Park ist schön.", "Park güzel.", "The park is beautiful.", "Sıfatlar"),
    ("schnell", "hızlı", "fast", "adjective", "Der Zug ist schnell.", "Tren hızlı.", "The train is fast.", "Sıfatlar"),
    ("langsam", "yavaş", "slow", "adjective", "Bitte sprich langsam.", "Lütfen yavaş konuş.", "Please speak slowly.", "Sıfatlar"),
    ("warm", "ılık; sıcak", "warm", "adjective", "Die Suppe ist warm.", "Çorba sıcak.", "The soup is warm.", "Sıfatlar"),
    ("kalt", "soğuk", "cold", "adjective", "Das Wasser ist kalt.", "Su soğuk.", "The water is cold.", "Sıfatlar"),
    ("teuer", "pahalı", "expensive", "adjective", "Das Hotel ist teuer.", "Otel pahalı.", "The hotel is expensive.", "Sıfatlar"),
    ("billig", "ucuz", "cheap", "adjective", "Das Ticket ist billig.", "Bilet ucuz.", "The ticket is cheap.", "Sıfatlar"),
    ("richtig", "doğru", "correct", "adjective", "Die Antwort ist richtig.", "Cevap doğru.", "The answer is correct.", "Sıfatlar"),
    ("heute", "bugün", "today", "adverb", "Heute habe ich Zeit.", "Bugün zamanım var.", "I have time today.", "Zaman"),
    ("morgen", "yarın", "tomorrow", "adverb", "Morgen arbeiten wir nicht.", "Yarın çalışmıyoruz.", "We do not work tomorrow.", "Zaman"),
    ("jetzt", "şimdi", "now", "adverb", "Ich komme jetzt.", "Şimdi geliyorum.", "I am coming now.", "Zaman"),
    ("hier", "burada", "here", "adverb", "Wir wohnen hier.", "Burada oturuyoruz.", "We live here.", "Temel"),
    ("dort", "orada", "there", "adverb", "Der Bahnhof ist dort.", "İstasyon orada.", "The station is there.", "Temel"),
    ("bitte", "lütfen", "please", "particle", "Ein Wasser, bitte.", "Bir su, lütfen.", "One water, please.", "Temel"),
    ("danke", "teşekkürler", "thank you", "particle", "Danke für deine Hilfe.", "Yardımın için teşekkürler.", "Thank you for your help.", "Temel"),
    ("ja", "evet", "yes", "particle", "Ja, das stimmt.", "Evet, doğru.", "Yes, that is correct.", "Temel"),
    ("nein", "hayır", "no", "particle", "Nein, heute nicht.", "Hayır, bugün değil.", "No, not today.", "Temel"),
    ("und", "ve", "and", "conjunction", "Anna und Leo lernen Deutsch.", "Anna ve Leo Almanca öğreniyor.", "Anna and Leo learn German.", "Temel"),
    ("aber", "ama", "but", "conjunction", "Klein, aber schön.", "Küçük ama güzel.", "Small but beautiful.", "Temel"),
]

_start = len(WORDS) + 1
WORDS.extend(_word(de, tr, en, pos, ex_de, ex_tr, ex_en, _start + i, deck)
             for i, (de, tr, en, pos, ex_de, ex_tr, ex_en, deck) in enumerate(_OTHER_DATA))

A1_WORDS = WORDS


def count() -> int:
    return len(WORDS)


def decks() -> list[str]:
    return sorted({w["deck"] for w in WORDS})
